name: Run Deployments

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    env:
      # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      # or if using AWS credentials directly
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: deploy listings
        uses: serverless/github-action@v3.1
        with:
          args: -c "cd ./subgraph-listings && yarn install && serverless deploy"
          entrypoint: /bin/sh
      - name: deploy bookings
        uses: serverless/github-action@v3.1
        with:
          args: -c "cd ./subgraph-bookings && yarn install && serverless deploy"
          entrypoint: /bin/sh
      - name: deploy accounts
        uses: serverless/github-action@v3.1
        with:
          args: -c "cd ./subgraph-accounts && yarn install && serverless deploy"
          entrypoint: /bin/sh
      - name: deploy reviews
        uses: serverless/github-action@v3.1
        with:
          args: -c "cd ./subgraph-reviews && yarn install && serverless deploy"
          entrypoint: /bin/sh
      - name: deploy payments
        uses: serverless/github-action@v3.1
        with:
          args: -c "cd ./subgraph-payments && yarn install && serverless deploy"
          entrypoint: /bin/sh
