# This job runs a schema check for the staging variant
name: Run schema checks

# It runs for every PR opened, updated and edited
on:
  pull_request:
    types: [opened, synchronize, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  schema_checks:
    name: schema_checks
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/environments
    environment: apollo

    # https://docs.github.com/en/actions/reference/encrypted-secrets
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsenv
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      APOLLO_GRAPH_REF: ${{ secrets.APOLLO_GRAPH_REF}}
      APOLLO_GRAPH_REF_STAGING: ${{secrets.APOLLO_GRAPH_REF_STAGING}}
      APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
      SUBGRAPH: listings

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh

          # Add Rover to the $GITHUB_PATH so it can be used in another step
          # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - name: Run check for listings against staging variant
        run: |
          rover subgraph check ${APOLLO_GRAPH_REF_STAGING} --schema ./subgraph-listings/schema.graphql --name listings
      - name: Run check for accounts against staging variant
        run: |
          rover subgraph check ${APOLLO_GRAPH_REF_STAGING} --schema ./subgraph-accounts/schema.graphql --name accounts
      - name: Run check for reviews against staging variant
        run: |
          rover subgraph check ${APOLLO_GRAPH_REF_STAGING} --schema ./subgraph-reviews/schema.graphql --name reviews
      - name: Run check for bookings against staging variant
        run: |
          rover subgraph check ${APOLLO_GRAPH_REF_STAGING} --schema ./subgraph-bookings/schema.graphql --name bookings
      - name: Run check for payments against staging variant
        run: |
          rover subgraph check ${APOLLO_GRAPH_REF_STAGING} --schema ./subgraph-payments/schema.graphql --name payments
